name: CD

on:
  release:
    types: [created]
  workflow_dispatch: # Allows manual triggering
    inputs:
      tag:
        description: 'Tag for this release'
        required: true
        default: 'v0.0.0'
  push: # Automatically triggers on push to main
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build
        run: |
          go build -v -o grabitsh-linux-amd64
          GOOS=darwin GOARCH=amd64 go build -v -o grabitsh-darwin-amd64
          GOOS=windows GOARCH=amd64 go build -v -o grabitsh-windows-amd64.exe

      - name: Generate SHA256
        run: |
          sha256sum grabitsh-linux-amd64 > grabitsh-linux-amd64.sha256
          sha256sum grabitsh-darwin-amd64 > grabitsh-darwin-amd64.sha256
          sha256sum grabitsh-windows-amd64.exe > grabitsh-windows-amd64.exe.sha256

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            grabitsh-linux-amd64
            grabitsh-darwin-amd64
            grabitsh-windows-amd64.exe
            grabitsh-linux-amd64.sha256
            grabitsh-darwin-amd64.sha256
            grabitsh-windows-amd64.exe.sha256
