name: CD

on:
  push:
    branches:
      - main  # Automatically triggers on every push to the main branch
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Required for creating releases and uploading assets

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build
        run: |
          go build -v -o grabitsh-linux-amd64
          GOOS=darwin GOARCH=amd64 go build -v -o grabitsh-darwin-amd64
          GOOS=windows GOARCH=amd64 go build -v -o grabitsh-windows-amd64.exe

      - name: Generate SHA256
        run: |
          sha256sum grabitsh-linux-amd64 > grabitsh-linux-amd64.sha256
          sha256sum grabitsh-darwin-amd64 > grabitsh-darwin-amd64.sha256
          sha256sum grabitsh-windows-amd64.exe > grabitsh-windows-amd64.exe.sha256

      - name: Create Tag
        id: create_tag
        run: |
          TAG="v1.0.$(date +'%s')"  # Generates a unique tag based on the current timestamp
          git config --global user.email "your-email@example.com"  # Set your GitHub email
          git config --global user.name "your-github-username"    # Set your GitHub username
          git tag $TAG
          git push origin $TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.create_tag.outputs.TAG }}  # Use the newly created tag
          files: |
            grabitsh-linux-amd64
            grabitsh-darwin-amd64
            grabitsh-windows-amd64.exe
            grabitsh-linux-amd64.sha256
            grabitsh-darwin-amd64.sha256
            grabitsh-windows-amd64.exe.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
