name: CI

on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
      - 'release/**'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Clean up workspace
      run: |
        rm -rf go/pkg/mod/github.com/fatih/color@v1.17.0

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Vet
      run: go vet ./...

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        skip-cache: true  # Skipping cache to avoid conflicts

    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: grabitsh
        path: grabitsh

  report:
    needs: build
    if: success()
    runs-on: ubuntu-latest
    steps:
    - name: Check build status
      run: |
        echo "Build and tests passed successfully!"
        echo "Ready for review and merge."
